import { sql } from 'drizzle-orm'
import {
  date,
  index,
  integer,
  numeric,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core'

import { newId } from '../id.js'
import { users } from './auth.js'
import { mediaAssets } from './media.js'
import { gameTypes, genres, locations } from './taxonomy.js'

/**
 * The library. One row per game the user owns.
 *
 * There is deliberately **no status column** — presence in this table means
 * owned, and play-state tracking was declined. See docs/adr.md ADR-013.
 */
export const games = pgTable(
  'games',
  {
    id: uuid('id').primaryKey().$defaultFn(newId),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),

    /** Null for a manually added game with no IGDB match. */
    igdbId: integer('igdb_id'),
    name: text('name').notNull(),
    /**
     * Generated by Postgres, not the application, so it can never drift from
     * `name`. Strips one leading article so "The Witcher 3" files under W.
     * packages/shared exports a matching sortName() for client-side preview,
     * but this expression is the authority.
     */
    sortName: text('sort_name')
      .notNull()
      .generatedAlwaysAs(sql`regexp_replace(name, '^(the|a|an)\\s+', '', 'i')`),

    summary: text('summary'),
    releaseDate: date('release_date'),
    igdbRating: numeric('igdb_rating', { precision: 4, scale: 1 }),

    gameTypeId: uuid('game_type_id').references(() => gameTypes.id, { onDelete: 'set null' }),
    coverAssetId: uuid('cover_asset_id').references(() => mediaAssets.id, { onDelete: 'set null' }),

    /** User-authored markdown. Sanitized at render, never at storage. */
    notes: text('notes'),
    acquiredAt: date('acquired_at'),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('games_user_sort_name_idx').on(t.userId, t.sortName),
    index('games_user_type_idx').on(t.userId, t.gameTypeId),
    index('games_user_created_idx').on(t.userId, t.createdAt),
    // NOTE: the partial unique index on (user_id, igdb_id) and the pg_trgm
    // index on name are appended by hand to the generated migration —
    // drizzle-kit cannot express either. See docs/database.md §6.
  ],
)

/**
 * A game can be in several locations at once (GOG *and* an external drive).
 * That is the whole point of the duplicate-purchase guard, so this is M:N
 * rather than a FK on games. See docs/adr.md ADR-004.
 */
export const gameLocations = pgTable(
  'game_locations',
  {
    gameId: uuid('game_id')
      .notNull()
      .references(() => games.id, { onDelete: 'cascade' }),
    locationId: uuid('location_id')
      .notNull()
      .references(() => locations.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.gameId, t.locationId] }),
    // Drives the "filter by location" direction of the query.
    index('game_locations_location_idx').on(t.locationId),
  ],
)

export const gameGenres = pgTable(
  'game_genres',
  {
    gameId: uuid('game_id')
      .notNull()
      .references(() => games.id, { onDelete: 'cascade' }),
    genreId: uuid('genre_id')
      .notNull()
      .references(() => genres.id, { onDelete: 'cascade' }),
  },
  (t) => [
    primaryKey({ columns: [t.gameId, t.genreId] }),
    index('game_genres_genre_idx').on(t.genreId),
  ],
)
